import type { Lang } from "@/i18n/dictionary";
const languageIndex: Record<Lang, number> = { en: 0, vi: 1, ru: 2, zh: 3, ko: 4, ja: 5 };
const copy = {
  title: [
    "Resort atlas",
    "Bản đồ khu nghỉ dưỡng",
    "Карта курорта",
    "度假村地图",
    "리조트 지도",
    "リゾートマップ",
  ],
  open: [
    "Explore the map",
    "Khám phá bản đồ",
    "Открыть карту",
    "探索地图",
    "지도 둘러보기",
    "マップを見る",
  ],
  locate: [
    "View on map",
    "Xem trên bản đồ",
    "Показать на карте",
    "在地图上查看",
    "지도에서 보기",
    "地図で見る",
  ],
  search: ["Find a place", "Tìm địa điểm", "Найти место", "查找地点", "장소 검색", "場所を検索"],
  all: ["All places", "Tất cả địa điểm", "Все места", "所有地点", "모든 장소", "すべての場所"],
  explore: ["Explore", "Khám phá", "Обзор", "探索", "둘러보기", "探索"],
  photos: ["Photo spots", "Điểm chụp ảnh", "Фотоместа", "拍照点", "포토 스폿", "撮影スポット"],
  walk: ["Walk", "Đi bộ", "Прогулка", "步行", "산책", "散策"],
  tour: [
    "Bensley Tour",
    "Tour Bensley",
    "Тур Bensley",
    "Bensley 导览",
    "벤슬리 투어",
    "ベンスリーツアー",
  ],
  close: ["Close map", "Đóng bản đồ", "Закрыть карту", "关闭地图", "지도 닫기", "地図を閉じる"],
  discover: [
    "Discover this place",
    "Khám phá địa điểm",
    "Подробнее о месте",
    "了解此处",
    "장소 자세히 보기",
    "この場所を見る",
  ],
  here: [
    "At this location",
    "Tại địa điểm này",
    "В этом месте",
    "此处的设施",
    "이곳의 시설",
    "この場所の施設",
  ],
  fit: [
    "View entire resort",
    "Xem toàn khu nghỉ dưỡng",
    "Весь курорт",
    "查看整个度假村",
    "리조트 전체 보기",
    "リゾート全体を表示",
  ],
  zoomIn: ["Zoom in", "Phóng to", "Приблизить", "放大", "확대", "拡大"],
  zoomOut: ["Zoom out", "Thu nhỏ", "Отдалить", "缩小", "축소", "縮小"],
  layers: [
    "Map options",
    "Tùy chọn bản đồ",
    "Настройки карты",
    "地图选项",
    "지도 옵션",
    "地図オプション",
  ],
  official: [
    "Official plan",
    "Sơ đồ chính thức",
    "Официальный план",
    "官方平面图",
    "공식 안내도",
    "公式案内図",
  ],
  illustrated: [
    "Illustrated map",
    "Bản đồ minh họa",
    "Иллюстрированная карта",
    "插画地图",
    "일러스트 지도",
    "イラストマップ",
  ],
  noResults: [
    "No matching places",
    "Không tìm thấy địa điểm",
    "Места не найдены",
    "未找到地点",
    "검색 결과가 없습니다",
    "該当する場所がありません",
  ],
  unavailable: [
    "The map is temporarily unavailable. Please try again later.",
    "Bản đồ tạm thời không khả dụng. Vui lòng thử lại sau.",
    "Карта временно недоступна. Попробуйте позже.",
    "地图暂时不可用，请稍后重试。",
    "지도를 일시적으로 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.",
    "現在マップを表示できません。しばらくしてからお試しください。",
  ],
  loading: [
    "Opening the atlas…",
    "Đang mở bản đồ…",
    "Открываем карту…",
    "正在打开地图…",
    "지도를 여는 중…",
    "マップを開いています…",
  ],
  note: [
    "Illustrated plan · not to scale",
    "Sơ đồ minh họa · không theo tỷ lệ",
    "Иллюстрированный план · не в масштабе",
    "示意图 · 非按比例绘制",
    "안내도 · 실제 축척과 다름",
    "案内図・縮尺は実際と異なります",
  ],
  walkNote: [
    "Discovery Trail · 4 km. Times are approximate walks to Nam Tram.",
    "Discovery Trail · 4 km. Thời gian đi bộ đến Nam Tram chỉ là ước tính.",
    "Discovery Trail · 4 км. Указано примерное время пешком до Nam Tram.",
    "Discovery Trail · 4 公里。时间为步行至 Nam Tram 的估算。",
    "Discovery Trail · 4 km. 표시 시간은 Nam Tram까지의 예상 도보 시간입니다.",
    "Discovery Trail・4 km。所要時間はNam Tramまでの徒歩の目安です。",
  ],
  tourNote: [
    "Design tour · a sequence of stops, not walking directions",
    "Tour thiết kế · thứ tự điểm tham quan, không phải chỉ dẫn đường đi",
    "Дизайн-тур · порядок остановок, не пешеходный маршрут",
    "设计导览 · 参观点顺序，并非步行导航",
    "디자인 투어 · 방문 순서이며 길 안내가 아닙니다",
    "デザインツアー・訪問順序であり、道案内ではありません",
  ],
  previous: [
    "Previous stop",
    "Điểm trước",
    "Предыдущая остановка",
    "上一站",
    "이전 정류장",
    "前のスポット",
  ],
  next: [
    "Next stop",
    "Điểm tiếp theo",
    "Следующая остановка",
    "下一站",
    "다음 정류장",
    "次のスポット",
  ],
  dismiss: [
    "Close place preview",
    "Đóng xem trước",
    "Закрыть описание",
    "关闭地点预览",
    "장소 미리보기 닫기",
    "場所のプレビューを閉じる",
  ],
  expand: ["More detail", "Chi tiết", "Подробнее", "更多详情", "자세히", "詳細を表示"],
  collapse: ["Less detail", "Thu gọn", "Свернуть", "收起详情", "접기", "詳細を閉じる"],
  landmark: [
    "Orientation landmark",
    "Mốc định hướng",
    "Ориентир",
    "定位地标",
    "위치 안내 지점",
    "位置の目印",
  ],
  gestures: [
    "Drag to explore. Pinch or use the buttons to zoom.",
    "Kéo để khám phá. Chụm ngón tay hoặc dùng nút để thu phóng.",
    "Перетаскивайте карту. Масштабируйте жестом или кнопками.",
    "拖动探索，双指缩放或使用按钮。",
    "드래그하여 둘러보고 두 손가락이나 버튼으로 확대하세요.",
    "ドラッグして移動。ピンチ操作またはボタンで拡大できます。",
  ],
} satisfies Record<string, readonly [string, string, string, string, string, string]>;
export type MapCopyKey = keyof typeof copy;
export const mapCopy = (lang: Lang, key: MapCopyKey): string => copy[key][languageIndex[lang]]!;
