import type { Lang } from "@/i18n/dictionary";
const languageIndex: Record<Lang, number> = { en: 0, vi: 1, ru: 2, zh: 3, ko: 4, ja: 5 };
const copy = {
  kicker: [
    "YOUR RESORT, YOUR WAY",
    "KHU NGHỈ DƯỠNG THEO CÁCH CỦA BẠN",
    "КУРОРТ В ВАШЕМ РИТМЕ",
    "随心探索度假村",
    "나만의 리조트 여행",
    "あなたらしいリゾートの旅",
  ],
  title: [
    "Choose your discovery",
    "Chọn hành trình khám phá",
    "Выберите своё открытие",
    "选择探索方式",
    "나만의 발견을 시작하세요",
    "発見の旅を選ぶ",
  ],
  journey: ["The journey", "Hành trình", "Путешествие", "开启旅程", "여정", "旅をはじめる"],
  journeyNote: [
    "From Heaven to Sea",
    "Từ Heaven xuống Sea",
    "От Heaven к Sea",
    "从 Heaven 到 Sea",
    "Heaven에서 Sea까지",
    "HeavenからSeaへ",
  ],
  map: [
    "Explore the resort map",
    "Khám phá bản đồ khu nghỉ dưỡng",
    "Откройте карту курорта",
    "探索度假村地图",
    "리조트 지도 둘러보기",
    "リゾートマップを探索",
  ],
  mapNote: [
    "Find your place in paradise",
    "Tìm góc thiên đường của bạn",
    "Найдите свой уголок рая",
    "寻找你的心仪之地",
    "나만의 낙원을 찾아보세요",
    "お気に入りの場所を見つけて",
  ],
  surprise: [
    "Surprise me",
    "Khám phá bất ngờ",
    "Удивите меня",
    "惊喜发现",
    "뜻밖의 발견",
    "偶然の出会い",
  ],
  surpriseNote: [
    "Find your next favourite place",
    "Tìm địa điểm yêu thích tiếp theo",
    "Найдите новое любимое место",
    "邂逅下一个心仪之地",
    "새로운 최애 장소를 찾아보세요",
    "次のお気に入りを見つけて",
  ],
  hint: [
    "Swipe to explore · Tap to discover",
    "Vuốt để khám phá · Chạm để xem",
    "Листайте и нажимайте, чтобы узнать больше",
    "滑动探索 · 轻点查看",
    "스와이프로 탐색 · 탭하여 자세히 보기",
    "スワイプで探索・タップで詳しく",
  ],
  previous: [
    "Previous discovery",
    "Khám phá trước",
    "Предыдущее место",
    "上一个发现",
    "이전 장소",
    "前のスポット",
  ],
  next: [
    "Next discovery",
    "Khám phá tiếp theo",
    "Следующее место",
    "下一个发现",
    "다음 장소",
    "次のスポット",
  ],
  again: [
    "Shuffle again",
    "Khám phá lượt mới",
    "Перемешать снова",
    "再次随机探索",
    "다시 섞기",
    "もう一度シャッフル",
  ],
  empty: [
    "New discoveries are on their way.",
    "Những khám phá mới sắp xuất hiện.",
    "Скоро здесь появятся новые открытия.",
    "更多精彩发现即将到来。",
    "새로운 발견을 준비하고 있어요.",
    "新たな発見を準備しています。",
  ],
} satisfies Record<string, readonly [string, string, string, string, string, string]>;
export type DiscoveryCopyKey = keyof typeof copy;
export const discoveryCopy = (lang: Lang, key: DiscoveryCopyKey): string =>
  copy[key][languageIndex[lang]]!;
