/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as HubIndexRouteImport } from './routes/_hub.index'
import { Route as HubDestinationIdRouteImport } from './routes/_hub.$destinationId'
import { Route as ApiResortPdfRouteImport } from './routes/api/resort-pdf'

const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const HubDestinationIdRoute = HubDestinationIdRouteImport.update({
  id: '/$destinationId',
  path: '/$destinationId',
  getParentRoute: () => HubRoute,
} as any)
const ApiResortPdfRoute = ApiResortPdfRouteImport.update({
  id: '/api/resort-pdf',
  path: '/api/resort-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HubIndexRoute
  '/$destinationId': typeof HubDestinationIdRoute
  '/api/resort-pdf': typeof ApiResortPdfRoute
}
export interface FileRoutesByTo {
  '/$destinationId': typeof HubDestinationIdRoute
  '/api/resort-pdf': typeof ApiResortPdfRoute
  '/': typeof HubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_hub': typeof HubRouteWithChildren
  '/_hub/$destinationId': typeof HubDestinationIdRoute
  '/api/resort-pdf': typeof ApiResortPdfRoute
  '/_hub/': typeof HubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$destinationId' | '/api/resort-pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/$destinationId' | '/api/resort-pdf' | '/'
  id:
    '__root__' | '/_hub' | '/_hub/$destinationId' | '/api/resort-pdf' | '/_hub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HubRoute: typeof HubRouteWithChildren
  ApiResortPdfRoute: typeof ApiResortPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/': {
      id: '/_hub/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/$destinationId': {
      id: '/_hub/$destinationId'
      path: '/$destinationId'
      fullPath: '/$destinationId'
      preLoaderRoute: typeof HubDestinationIdRouteImport
      parentRoute: typeof HubRoute
    }
    '/api/resort-pdf': {
      id: '/api/resort-pdf'
      path: '/api/resort-pdf'
      fullPath: '/api/resort-pdf'
      preLoaderRoute: typeof ApiResortPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HubRouteChildren {
  HubDestinationIdRoute: typeof HubDestinationIdRoute
  HubIndexRoute: typeof HubIndexRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubDestinationIdRoute: HubDestinationIdRoute,
  HubIndexRoute: HubIndexRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HubRoute: HubRouteWithChildren,
  ApiResortPdfRoute: ApiResortPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
