-- Keep notices to a short title and one factual sentence.
begin;
update public.destination_notices set title = 'Temporary location', body = 'La Maison 1888 dinner is temporarily served on Heaven level.' where id = 'la-maison-heaven-refurbishment';
update public.destination_notice_translations set title = 'Địa điểm tạm thời', body = 'Bữa tối La Maison 1888 tạm thời được phục vụ tại tầng Heaven.', source_title = 'Temporary location', source_body = 'La Maison 1888 dinner is temporarily served on Heaven level.' where notice_id = 'la-maison-heaven-refurbishment' and locale = 'vi';
update public.destination_notice_translations set title = 'Временное расположение', body = 'Ужин La Maison 1888 временно подаётся на уровне Heaven.', source_title = 'Temporary location', source_body = 'La Maison 1888 dinner is temporarily served on Heaven level.' where notice_id = 'la-maison-heaven-refurbishment' and locale = 'ru';
update public.destination_notice_translations set title = '临时用餐地点', body = 'La Maison 1888 晚餐暂时于 Heaven 层供应。', source_title = 'Temporary location', source_body = 'La Maison 1888 dinner is temporarily served on Heaven level.' where notice_id = 'la-maison-heaven-refurbishment' and locale = 'zh';
update public.destination_notice_translations set title = '임시 운영 장소', body = 'La Maison 1888 저녁 식사는 임시로 Heaven 레벨에서 제공됩니다.', source_title = 'Temporary location', source_body = 'La Maison 1888 dinner is temporarily served on Heaven level.' where notice_id = 'la-maison-heaven-refurbishment' and locale = 'ko';
update public.destination_notice_translations set title = '一時的な会場変更', body = 'La Maison 1888のディナーは一時的にHeavenレベルで提供しています。', source_title = 'Temporary location', source_body = 'La Maison 1888 dinner is temporarily served on Heaven level.' where notice_id = 'la-maison-heaven-refurbishment' and locale = 'ja';
update public.destination_notices set title = 'Temporary closure', body = 'Buffalo Bar is temporarily closed during La Maison 1888’s refurbishment.' where id = 'buffalo-bar-refurbishment';
update public.destination_notice_translations set title = 'Tạm thời đóng cửa', body = 'Buffalo Bar tạm thời đóng cửa trong thời gian cải tạo La Maison 1888.', source_title = 'Temporary closure', source_body = 'Buffalo Bar is temporarily closed during La Maison 1888’s refurbishment.' where notice_id = 'buffalo-bar-refurbishment' and locale = 'vi';
update public.destination_notice_translations set title = 'Временно закрыто', body = 'Buffalo Bar временно закрыт на время обновления La Maison 1888.', source_title = 'Temporary closure', source_body = 'Buffalo Bar is temporarily closed during La Maison 1888’s refurbishment.' where notice_id = 'buffalo-bar-refurbishment' and locale = 'ru';
update public.destination_notice_translations set title = '暂时关闭', body = 'La Maison 1888 翻修期间，Buffalo Bar 暂时关闭。', source_title = 'Temporary closure', source_body = 'Buffalo Bar is temporarily closed during La Maison 1888’s refurbishment.' where notice_id = 'buffalo-bar-refurbishment' and locale = 'zh';
update public.destination_notice_translations set title = '임시 휴업', body = 'La Maison 1888 리노베이션 기간 동안 Buffalo Bar는 임시 휴업합니다.', source_title = 'Temporary closure', source_body = 'Buffalo Bar is temporarily closed during La Maison 1888’s refurbishment.' where notice_id = 'buffalo-bar-refurbishment' and locale = 'ko';
update public.destination_notice_translations set title = '一時休業', body = 'La Maison 1888の改装期間中、Buffalo Barは一時休業しています。', source_title = 'Temporary closure', source_body = 'Buffalo Bar is temporarily closed during La Maison 1888’s refurbishment.' where notice_id = 'buffalo-bar-refurbishment' and locale = 'ja';
commit;

