begin;
create table if not exists public.destination_notices (
  id text primary key,
  destination_id text not null references public.destinations(id) on delete cascade,
  kind text not null default 'information' check(kind in ('information','relocation','closure')),
  title text not null check(length(trim(title)) > 0),
  body text not null check(length(trim(body)) > 0),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  published boolean not null default false,
  display_order integer not null default 0,
  source_url text not null check(source_url like 'https://www.danang.intercontinental.com/%'),
  verified_on date not null,
  updated_at timestamptz not null default now(),
  check(ends_at is null or ends_at > starts_at)
);
create table if not exists public.destination_notice_translations (
  notice_id text not null references public.destination_notices(id) on delete cascade,
  locale text not null check(locale in ('vi','ru','zh','ko','ja')),
  title text not null check(length(trim(title)) > 0),
  body text not null check(length(trim(body)) > 0),
  source_title text not null,
  source_body text not null,
  published boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key(notice_id,locale)
);
create index if not exists destination_notices_public_idx
  on public.destination_notices(destination_id,display_order) where published;
alter table public.destination_notices enable row level security;
alter table public.destination_notice_translations enable row level security;
revoke all on public.destination_notices,public.destination_notice_translations from anon,authenticated;
grant select on public.destination_notices,public.destination_notice_translations to anon,authenticated;
create policy "Current published destination notices" on public.destination_notices
  for select to anon,authenticated using (
    published and starts_at <= now() and (ends_at is null or ends_at > now())
    and exists(select 1 from public.destinations d where d.id=destination_id and d.active)
  );
create policy "Current published notice translations" on public.destination_notice_translations
  for select to anon,authenticated using (
    published and exists(select 1 from public.destination_notices n where n.id=notice_id
      and n.title=source_title and n.body=source_body)
  );
create or replace function public.touch_destination_notice_timestamp()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at=now(); return new; end;
$$;
create trigger destination_notice_updated before update on public.destination_notices
for each row execute function public.touch_destination_notice_timestamp();
create trigger destination_notice_translation_updated before update on public.destination_notice_translations
for each row execute function public.touch_destination_notice_timestamp();
create or replace view public.published_destination_notices with (security_invoker=true) as
select n.id,n.destination_id,n.kind,n.title,n.body,n.starts_at,n.ends_at,n.display_order,
  coalesce((select jsonb_agg(jsonb_build_object('locale',t.locale,'title',t.title,'body',t.body,
    'source_title',t.source_title,'source_body',t.source_body) order by t.locale)
    from public.destination_notice_translations t where t.notice_id=n.id and t.published), '[]'::jsonb) as translations
from public.destination_notices n
where n.published and n.starts_at <= now() and (n.ends_at is null or n.ends_at > now());
grant select on public.published_destination_notices to anon,authenticated;
insert into public.destination_notices(id,destination_id,kind,title,body,starts_at,source_url,verified_on,published) values('la-maison-heaven-refurbishment','la-maison-1888','relocation','Temporarily served on Heaven level','During refurbishment, the La Maison 1888 dining experience is hosted on Heaven level with a five-course menu by Chef Christian Le Squer. Reservations are recommended.','2026-10-06T00:00:00+07:00','https://www.danang.intercontinental.com/dining/la-maison-1888/','2026-10-06',true) on conflict(id) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('la-maison-heaven-refurbishment','vi','Tạm thời phục vụ tại tầng Heaven','Trong thời gian cải tạo, trải nghiệm La Maison 1888 diễn ra tại tầng Heaven với thực đơn năm món của đầu bếp Christian Le Squer. Nên đặt bàn trước.','Temporarily served on Heaven level','During refurbishment, the La Maison 1888 dining experience is hosted on Heaven level with a five-course menu by Chef Christian Le Squer. Reservations are recommended.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('la-maison-heaven-refurbishment','ru','Временно на уровне Heaven','На время ремонта ужины La Maison 1888 проходят на уровне Heaven с меню из пяти блюд от Кристиана Ле Скера. Рекомендуется предварительное бронирование.','Temporarily served on Heaven level','During refurbishment, the La Maison 1888 dining experience is hosted on Heaven level with a five-course menu by Chef Christian Le Squer. Reservations are recommended.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('la-maison-heaven-refurbishment','zh','暂于Heaven层级提供用餐体验','翻修期间，La Maison 1888用餐体验设于Heaven层级，提供Christian Le Squer主厨的五道式菜单。建议提前预约。','Temporarily served on Heaven level','During refurbishment, the La Maison 1888 dining experience is hosted on Heaven level with a five-course menu by Chef Christian Le Squer. Reservations are recommended.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('la-maison-heaven-refurbishment','ko','Heaven 층에서 임시 운영','보수 기간 중 La Maison 1888의 식사는 Heaven 층에서 Christian Le Squer 셰프의 5코스 메뉴로 제공됩니다. 사전 예약을 권장합니다.','Temporarily served on Heaven level','During refurbishment, the La Maison 1888 dining experience is hosted on Heaven level with a five-course menu by Chef Christian Le Squer. Reservations are recommended.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('la-maison-heaven-refurbishment','ja','Heaven階で一時的に営業','改装期間中、La Maison 1888の食事はHeaven階でChristian Le Squerシェフの5品コースとして提供されます。事前のご予約をおすすめします。','Temporarily served on Heaven level','During refurbishment, the La Maison 1888 dining experience is hosted on Heaven level with a five-course menu by Chef Christian Le Squer. Reservations are recommended.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notices(id,destination_id,kind,title,body,starts_at,source_url,verified_on,published) values('buffalo-bar-refurbishment','buffalo-bar','closure','Temporarily closed for refurbishment','Buffalo Bar is temporarily unavailable while La Maison 1888 undergoes refurbishment. A reopening date has not been announced on the official page.','2026-10-06T00:00:00+07:00','https://www.danang.intercontinental.com/dining/buffalo-bar/','2026-10-06',true) on conflict(id) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('buffalo-bar-refurbishment','vi','Tạm thời đóng cửa để cải tạo','Buffalo Bar tạm ngừng phục vụ trong thời gian La Maison 1888 cải tạo. Trang chính thức chưa công bố ngày mở lại.','Temporarily closed for refurbishment','Buffalo Bar is temporarily unavailable while La Maison 1888 undergoes refurbishment. A reopening date has not been announced on the official page.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('buffalo-bar-refurbishment','ru','Временно закрыт на ремонт','Buffalo Bar временно недоступен на время ремонта La Maison 1888. Дата открытия на официальной странице пока не объявлена.','Temporarily closed for refurbishment','Buffalo Bar is temporarily unavailable while La Maison 1888 undergoes refurbishment. A reopening date has not been announced on the official page.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('buffalo-bar-refurbishment','zh','因翻修暂时关闭','La Maison 1888翻修期间，Buffalo Bar暂不开放。官方页面尚未公布重新开放日期。','Temporarily closed for refurbishment','Buffalo Bar is temporarily unavailable while La Maison 1888 undergoes refurbishment. A reopening date has not been announced on the official page.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('buffalo-bar-refurbishment','ko','보수 공사로 임시 휴업','La Maison 1888 보수 기간에는 Buffalo Bar를 이용할 수 없습니다. 공식 페이지에는 재개장 날짜가 아직 공지되지 않았습니다.','Temporarily closed for refurbishment','Buffalo Bar is temporarily unavailable while La Maison 1888 undergoes refurbishment. A reopening date has not been announced on the official page.',true) on conflict(notice_id,locale) do nothing;
insert into public.destination_notice_translations(notice_id,locale,title,body,source_title,source_body,published) values('buffalo-bar-refurbishment','ja','改装のため一時休業','La Maison 1888の改装期間中、Buffalo Barは休業しています。公式ページでは再開日はまだ発表されていません。','Temporarily closed for refurbishment','Buffalo Bar is temporarily unavailable while La Maison 1888 undergoes refurbishment. A reopening date has not been announced on the official page.',true) on conflict(notice_id,locale) do nothing;
update public.destinations set detail_description='Discover refined French cuisine inspired by Chef Christian Le Squer, where classical technique meets creative, seasonal flavours. Thoughtful wine pairings and attentive service shape an intimate dining experience that celebrates both culinary craftsmanship and the resort’s distinctive character.' where id='la-maison-1888';
update public.destination_translations set detail_description='Khám phá ẩm thực Pháp tinh tế theo cảm hứng của đầu bếp Christian Le Squer, nơi kỹ thuật cổ điển hòa cùng hương vị sáng tạo theo mùa. Rượu vang kết hợp hài hòa và phục vụ chu đáo tạo nên trải nghiệm đầy dấu ấn riêng của resort.',source_detail_description='Discover refined French cuisine inspired by Chef Christian Le Squer, where classical technique meets creative, seasonal flavours. Thoughtful wine pairings and attentive service shape an intimate dining experience that celebrates both culinary craftsmanship and the resort’s distinctive character.' where destination_id='la-maison-1888' and locale='vi';
update public.destination_translations set detail_description='Откройте изысканную французскую кухню Кристиана Ле Скера, соединяющую классическую технику с творческими сезонными вкусами. Продуманные винные сочетания и внимательный сервис создают камерный вечер, раскрывающий кулинарное мастерство и неповторимый характер курорта.',source_detail_description='Discover refined French cuisine inspired by Chef Christian Le Squer, where classical technique meets creative, seasonal flavours. Thoughtful wine pairings and attentive service shape an intimate dining experience that celebrates both culinary craftsmanship and the resort’s distinctive character.' where destination_id='la-maison-1888' and locale='ru';
update public.destination_translations set detail_description='探索Christian Le Squer主厨启发的精致法国料理，感受经典技法与创意时令风味的融合。用心搭配的葡萄酒与细致服务营造私密用餐体验，展现烹饪匠心与度假村独特风格。',source_detail_description='Discover refined French cuisine inspired by Chef Christian Le Squer, where classical technique meets creative, seasonal flavours. Thoughtful wine pairings and attentive service shape an intimate dining experience that celebrates both culinary craftsmanship and the resort’s distinctive character.' where destination_id='la-maison-1888' and locale='zh';
update public.destination_translations set detail_description='Christian Le Squer 셰프의 영감을 담은 프랑스 요리를 만나보세요. 고전적인 기법과 창의적인 제철 풍미, 세심한 와인 페어링과 서비스가 어우러져 요리의 장인 정신과 리조트만의 개성을 느끼는 식사를 선사합니다.',source_detail_description='Discover refined French cuisine inspired by Chef Christian Le Squer, where classical technique meets creative, seasonal flavours. Thoughtful wine pairings and attentive service shape an intimate dining experience that celebrates both culinary craftsmanship and the resort’s distinctive character.' where destination_id='la-maison-1888' and locale='ko';
update public.destination_translations set detail_description='Christian Le Squerシェフの感性が息づくフランス料理を。伝統的な技法と創造的な季節の味わい、丁寧なワインペアリングとサービスが、料理の技とリゾートらしさを感じる特別なひとときを彩ります。',source_detail_description='Discover refined French cuisine inspired by Chef Christian Le Squer, where classical technique meets creative, seasonal flavours. Thoughtful wine pairings and attentive service shape an intimate dining experience that celebrates both culinary craftsmanship and the resort’s distinctive character.' where destination_id='la-maison-1888' and locale='ja';
update public.destinations set detail_description='Step into an intimate hideaway within La Maison 1888 for an aperitif, a glass of Champagne or a carefully crafted cocktail. Buffalo Bar offers an elegant setting to begin an evening or linger over a digestif after dinner.' where id='buffalo-bar';
update public.destination_translations set detail_description='Ghé không gian riêng tư trong La Maison 1888 để thưởng thức rượu khai vị, Champagne hoặc cocktail pha chế tinh tế. Buffalo Bar là điểm hẹn thanh lịch để mở đầu buổi tối hay nhâm nhi rượu digestif sau bữa ăn.',source_detail_description='Step into an intimate hideaway within La Maison 1888 for an aperitif, a glass of Champagne or a carefully crafted cocktail. Buffalo Bar offers an elegant setting to begin an evening or linger over a digestif after dinner.' where destination_id='buffalo-bar' and locale='vi';
update public.destination_translations set detail_description='Загляните в уединённый уголок La Maison 1888 ради аперитива, бокала шампанского или искусно приготовленного коктейля. Элегантная атмосфера Buffalo Bar располагает к началу приятного вечера или неторопливому дижестиву после ужина.',source_detail_description='Step into an intimate hideaway within La Maison 1888 for an aperitif, a glass of Champagne or a carefully crafted cocktail. Buffalo Bar offers an elegant setting to begin an evening or linger over a digestif after dinner.' where destination_id='buffalo-bar' and locale='ru';
update public.destination_translations set detail_description='走进La Maison 1888内的私密空间，品尝餐前酒、香槟或精心调制的鸡尾酒。Buffalo Bar以优雅氛围迎接夜晚的开始，也适合在晚餐后悠然享用一杯餐后酒。',source_detail_description='Step into an intimate hideaway within La Maison 1888 for an aperitif, a glass of Champagne or a carefully crafted cocktail. Buffalo Bar offers an elegant setting to begin an evening or linger over a digestif after dinner.' where destination_id='buffalo-bar' and locale='zh';
update public.destination_translations set detail_description='La Maison 1888 안의 아늑한 공간에서 아페리티프, 샴페인 또는 정성껏 만든 칵테일을 즐겨보세요. Buffalo Bar의 우아한 분위기는 저녁을 시작하거나 식사 후 디제스티프와 함께 여유를 즐기기에 좋습니다.',source_detail_description='Step into an intimate hideaway within La Maison 1888 for an aperitif, a glass of Champagne or a carefully crafted cocktail. Buffalo Bar offers an elegant setting to begin an evening or linger over a digestif after dinner.' where destination_id='buffalo-bar' and locale='ko';
update public.destination_translations set detail_description='La Maison 1888の落ち着いた隠れ家で、アペリティフやシャンパン、丁寧に作られたカクテルを。Buffalo Barの優雅な空間は、夜の始まりにも、夕食後にディジェスティフをゆっくり味わう時間にも最適です。',source_detail_description='Step into an intimate hideaway within La Maison 1888 for an aperitif, a glass of Champagne or a carefully crafted cocktail. Buffalo Bar offers an elegant setting to begin an evening or linger over a digestif after dinner.' where destination_id='buffalo-bar' and locale='ja';
update public.destinations set detail_description='Explore La Maison 1888’s collection of rare vintages and renowned wine estates. With the sommelier team’s guidance, discover wines that reflect your tastes, learn the stories behind exceptional bottles and find thoughtful pairings to complement a memorable meal.' where id='wine-cellar';
update public.destination_translations set detail_description='Khám phá bộ sưu tập vang quý hiếm và các nhà rượu danh tiếng của La Maison 1888. Cùng đội ngũ sommelier, tìm hương vị hợp sở thích, lắng nghe câu chuyện những chai vang đặc biệt và chọn cách kết hợp món ăn đầy tinh tế.',source_detail_description='Explore La Maison 1888’s collection of rare vintages and renowned wine estates. With the sommelier team’s guidance, discover wines that reflect your tastes, learn the stories behind exceptional bottles and find thoughtful pairings to complement a memorable meal.' where destination_id='wine-cellar' and locale='vi';
update public.destination_translations set detail_description='Познакомьтесь с редкими винами и известными хозяйствами коллекции La Maison 1888. Сомелье помогут найти вина по вашему вкусу, узнать истории выдающихся бутылок и подобрать сочетания, которые дополнят незабываемый ужин.',source_detail_description='Explore La Maison 1888’s collection of rare vintages and renowned wine estates. With the sommelier team’s guidance, discover wines that reflect your tastes, learn the stories behind exceptional bottles and find thoughtful pairings to complement a memorable meal.' where destination_id='wine-cellar' and locale='ru';
update public.destination_translations set detail_description='探索La Maison 1888珍稀年份佳酿与著名酒庄的收藏。在侍酒师团队的引导下，发现符合您口味的葡萄酒，了解非凡酒款背后的故事，并寻找为难忘餐点增添风味的搭配。',source_detail_description='Explore La Maison 1888’s collection of rare vintages and renowned wine estates. With the sommelier team’s guidance, discover wines that reflect your tastes, learn the stories behind exceptional bottles and find thoughtful pairings to complement a memorable meal.' where destination_id='wine-cellar' and locale='zh';
update public.destination_translations set detail_description='La Maison 1888의 희귀 빈티지와 유명 와이너리 컬렉션을 만나보세요. 소믈리에 팀의 안내로 취향에 맞는 와인을 찾고 특별한 병에 담긴 이야기를 알아보며, 기억에 남을 식사를 위한 페어링을 발견해 보세요.',source_detail_description='Explore La Maison 1888’s collection of rare vintages and renowned wine estates. With the sommelier team’s guidance, discover wines that reflect your tastes, learn the stories behind exceptional bottles and find thoughtful pairings to complement a memorable meal.' where destination_id='wine-cellar' and locale='ko';
update public.destination_translations set detail_description='La Maison 1888が収蔵する希少なヴィンテージや名門ワイナリーのワインを。ソムリエの案内で好みに合う一本を見つけ、特別なボトルの物語に触れ、思い出に残る食事を彩る組み合わせを探しましょう。',source_detail_description='Explore La Maison 1888’s collection of rare vintages and renowned wine estates. With the sommelier team’s guidance, discover wines that reflect your tastes, learn the stories behind exceptional bottles and find thoughtful pairings to complement a memorable meal.' where destination_id='wine-cellar' and locale='ja';
commit;
